# Generated by Django 4.2.4 on 2023-12-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistrooapp_admin', '0006_alter_menuu_price_full_alter_menuu_price_half'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_date', models.DateField(unique=True)),
                ('theme', models.CharField(blank=True, max_length=255)),
                ('recommenders', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-menu_date'],
            },
        ),
    ]
