# Generated by Django 4.2.4 on 2023-12-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistrooapp_admin', '0007_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='recommenders',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
