# Generated by Django 4.2.4 on 2023-12-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistrooapp_admin', '0008_alter_theme_recommenders_alter_theme_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuu',
            name='price_half',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
    ]
