# Generated by Django 4.2.4 on 2023-12-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistrooapp_admin', '0009_alter_menuu_price_half'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuu',
            name='price_half',
            field=models.DecimalField(blank=True, decimal_places=2, default='0,00', max_digits=4, null=True),
        ),
    ]
