# Generated by Django 4.2.4 on 2023-12-17 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistrooapp_admin', '0011_alter_menuu_price_half'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Toidu kategooria'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_sort_id',
            field=models.PositiveIntegerField(verbose_name='Järjestus nr'),
        ),
        migrations.AlterField(
            model_name='menuu',
            name='price_full',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='menuu',
            name='price_half',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
