# Generated by Django 4.2.4 on 2023-12-21 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistrooapp_admin', '0012_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuu',
            name='price_full',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0, 'Sobib 0 või suurem')]),
        ),
        migrations.AlterField(
            model_name='menuu',
            name='price_half',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0, 'Sobib 0 või suurem')]),
        ),
    ]
