# Generated by Django 4.2.4 on 2024-01-30 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistrooapp_admin', '0013_alter_menuu_price_full_alter_menuu_price_half'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuu',
            options={'ordering': ['-menu_date', 'category_name', 'id']},
        ),
        migrations.AddField(
            model_name='menuu',
            name='is_hided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_sort_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='menuu',
            name='price_full',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0, 'Väärtus peab olema 0 või 0-st suurem number')]),
        ),
        migrations.AlterField(
            model_name='menuu',
            name='price_half',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0, 'Väärtus peab olema 0 või 0-st suurem number')]),
        ),
    ]
